"""empty message

Revision ID: bada78e9a9a8
Revises: e19fd729888d
Create Date: 2017-11-25 03:33:37.355463

"""

# revision identifiers, used by Alembic.
revision = 'bada78e9a9a8'
down_revision = 'e19fd729888d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("Altering column")
    op.alter_column('db_files', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('db_files_id_seq'::regclass)"))
    print("Adding new columns")
    op.add_column('db_files', sa.Column('imgx', sa.Integer(), nullable=True))
    op.add_column('db_files', sa.Column('imgy', sa.Integer(), nullable=True))
    op.add_column('db_files', sa.Column('phash', sa.BigInteger(), nullable=True))
    print("Creating phash index")
    op.create_index('phash_bktree_idx', 'db_files', [sa.text('phash bktree_ops')], unique=False, postgresql_using='spgist')
    print("Done")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phash_bktree_idx', table_name='db_files')
    op.alter_column('db_files', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('db_files_id_seq'::regclass)"))
    op.drop_column('db_files', 'phash')
    op.drop_column('db_files', 'imgy')
    op.drop_column('db_files', 'imgx')
    # ### end Alembic commands ###
